---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/
resources:
- route.yml

images:
- name: "play-scala-grpc-example"
  newName: "docker-registry-default.centralpark.lightbend.com/play-scala-grpc-example/play-scala-grpc-example"
  newTag: "1.0-SNAPSHOT"